services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/main-domain.conf.template:/etc/nginx/templates/main-domain.conf.template
      - ./nginx/auth-domain.conf.template:/etc/nginx/templates/auth-domain.conf.template
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/www:/var/www:ro
      - ./nginx/ssl:/etc/letsencrypt
    env_file:
      - .env
    depends_on:
      - core
      - workflow
      - vue-portal
      - portal
      - workflow-portal
      - finmars-start-page
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
    env_file:
      - .env
    ports:
      - "80:80" 
    command: [
      "certonly",
      "--standalone",
      "--non-interactive",
      "--agree-tos",
      "-d", "${MAIN_DOMAIN_NAME}",
      "-d", "${AUTH_DOMAIN_NAME}"
    ]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    restart: always
    command: start --import-realm
    volumes:
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf:ro
      - ./nginx/ssl:/etc/letsencrypt
      - ./keycloak/themes/finmars:/opt/keycloak/themes/finmars
      - ./keycloak/data/:/opt/keycloak/data/import
    env_file:
      - .env
    environment:
      - KC_DB=postgres
      - KC_BOOTSTRAP_ADMIN_USERNAME=${ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - KEYCLOAK_ADMIN=${ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import
    depends_on:
      - db_keycloak
    ports:
      - "8004:8080"

  core:
    build:
      context: ../finmars-core
    restart: always
    volumes:
      - ../finmars-core/poms:/var/app/poms
      - ./storage:/var/app/finmars_data
    env_file:
      - .env
    environment:
      - DB_NAME=core_realm00000
      # - LOCAL=1
    depends_on:
      - db
      - rabbitmq
      - redis
      - keycloak

  core-worker:
    build:
      context: ../finmars-core
    restart: always
    volumes:
      - ./storage:/var/app/finmars_data
    env_file:
      - .env
    environment:
      - DB_NAME=core_realm00000
      - DJANGO_SETTINGS_MODULE=poms_app.settings
      - INSTANCE_TYPE=worker
    depends_on:
      - db
      - rabbitmq
      - redis

  core-migration:
    build:
      context: ../finmars-core
    volumes:
      - ../finmars-core/poms:/var/app/poms
    env_file:
      - .env
    environment:
      - DB_NAME=core_realm00000
      - INSTANCE_TYPE=job
    depends_on:
      - db
      - redis

  workflow:
    build:
      context: ../finmars-workflow
    restart: always
    volumes:
      - ./storage:/var/app/finmars_data
      - ../finmars-workflow/workflow:/var/app/workflow
    env_file:
      - .env
    environment:
      - DB_NAME=workflow_realm00000
      - DOMAIN_NAME=${MAIN_DOMAIN_NAME}
      # - LOCAL=1
    depends_on:
      - db
      - rabbitmq
      - redis
      - keycloak

  workflow-worker:
    build:
      context: ../finmars-workflow
    restart: always
    volumes:
      - ./storage:/var/app/finmars_data
    env_file:
      - .env
    environment:
      - DB_NAME=workflow_realm00000
      - INSTANCE_TYPE=worker
      - DJANGO_SETTINGS_MODULE=workflow_app.settings
      - DOMAIN_NAME=${MAIN_DOMAIN_NAME}
    depends_on:
      - db
      - rabbitmq
      - redis
      - keycloak

  workflow-scheduler:
    build:
      context: ../finmars-workflow
    restart: always
    volumes:
      - ./storage:/var/app/finmars_data
    env_file:
      - .env
    environment:
      - DB_NAME=workflow_realm00000
      - INSTANCE_TYPE=beat
      - DJANGO_SETTINGS_MODULE=workflow_app.settings
      - DOMAIN_NAME=${MAIN_DOMAIN_NAME}
    depends_on:
      - db
      - redis

  workflow-migration:
    build:
      context: ../finmars-workflow
    volumes:
      - ./storage:/var/app/finmars_data
    env_file:
      - .env
    environment:
      - DB_NAME=workflow_realm00000
      - INSTANCE_TYPE=job
      - DOMAIN_NAME=${MAIN_DOMAIN_NAME}
    depends_on:
      - db
      - redis

  finmars-start-page:
    image: finmars/finmars-start-page:1.19.0-stable
    restart: always
    env_file:
      - .env

  portal:
    image: finmars/finmars-portal:1.19.0-stable
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080" 

  vue-portal:
    image: finmars/finmars-vue-portal:1.19.3-rc
    restart: always
    environment:
      - NUXT_APP_BUILD_ASSETS_DIR=/realm00000/v/_nuxt/
    env_file:
      - .env

  workflow-portal:
    image: finmars/finmars-workflow-portal:1.19.2-rc
    restart: always
    environment:
      - NUXT_APP_BUILD_ASSETS_DIR=/realm00000/w/_nuxt/
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    stdin_open: true
    tty: true
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"    

  db_keycloak:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=${KC_DB_URL_DATABASE}
      - POSTGRES_USER=${KC_DB_USERNAME}
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
    stdin_open: true
    tty: true
    volumes:
      - ./postgres_data_keycloak:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
    stdin_open: true
    tty: true

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  postgres_data_keycloak:
